#! /usr/bin/env sh
#
# MIT License
#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

set -eu

if [ -e .version ]; then
    SIM_DEFAULT_VERSION=$(cat .version)
else
    SIM_DEFAULT_VERSION=lastest
fi

SIM_VERSION=${SIM_VERSION:=$SIM_DEFAULT_VERSION}

if [ -z ${SIM_VERSION+x} ]; then
    echo "SIM_VERSION is not set"
    exit 1
fi

container_args=""
for (( i=0; i <= "$#"; i++ )); do
    next=$(( i + 1 ))
    if [[ "$next" -le "$#" ]]; then
        case "${!i}" in
            "--output")
                output_dir=${!next}
                if [ -d "$output_dir" ]; then
                    output_dir=$(realpath $output_dir)
                    container_args="$container_args -v $output_dir:$output_dir"
                fi
                ;;
        esac
    fi
done

echo "ARGS: $@"
# exec sh -c "docker run -it --rm --user $(id -u):$(id -u) simulation-environment:$SIM_VERSION $@"
docker run -it --rm --user $(id -u):$(id -u) simulation-environment:$SIM_VERSION $@
